### ISSUE TITLE
Bytecode compiler

### ISSUE THREAD

**Issue by YorickPeterse** [inko-lang/inko#10]
A bytecode compiler has to be implemented. This compiler takes an AST of a file and generates the corresponding bytecode. The bytecode is then cached in a file (see #9) which is then fed to the VM.

## TODO

This is not a final list and is expected to change somewhat as I continue work on the compiler:

* [ ] Add support for all language features in the `ModuleBody` pass
* [x] Rework type inference. This is currently a separate pass so methods can refer to each other regardless of order. This however leads to quite a bit of duplication logic and makes it hard to figure out what the right types are when dealing with raw instructions. Getting this right is crucial to ensure good type analysis for some of the core objects. 
  * Preferably this pass is merged into the ModuleBody pass and referring to methods-defined-later-but-on-the-same-receiver are handled in a different way.
  * At the same time keeping this in a separate pass makes the `ModuleBody` pass simpler
  * A downside of having this in a separate pass is that you can refer to a constant before it's defined, leading to runtime errors
  * **Solution:** hoisting of constant, object, trait, and method definitions: 8b2e75c14e0d96b37394150476aac884a2dc287a
* [ ] Remove `TIR::Builder` once all code has been ported over to the multi-pass compiler
* [ ] Remove `TypeLookup#initialize_type`
* [x] Move the instruction helpers from `CodeObject` (e.g. `set_attribute`) into the `ModuleBody` pass. The separation leads to a rather clunky API
* [ ] Add an optimisation pass with some basic optimisations
  * [ ] Constant folding
  * [ ] Tail-call optimisation
    * This will be required to implement loops without having to mess with raw instructions and hard-coded instruction offsets for the various goto VM instructions
  * [ ] Inlining methods that simply return instance attributes
    * This ensures simple getter methods don't introduce additional overhead

**Comment by YorickPeterse** [comment]
A lot of work is being done on this in the `compiler/` directory, which contains a Ruby based compiler. This won't be the final compiler, instead it aims to be a compiler that's good enough to allow building the language. Once enough parts are in place I aim to make the compiler self hosting.
