### ISSUE TITLE
Stop building pre-compiled packages for ienv

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#288]
As part of our release process, we build two types of packages:

1. A source archive, which can be used to install Inko from source; without
   having to Git clone it.
1. An archive containing the pre-compiled VM, runtime, and compiler.

The goal of this setup was to make installing Inko fast on platforms for which
pre-compiled binaries are available, with a fallback for building from source if
no pre-compiled binaries could be found.

I'm not convinced this is as useful as hoped. In addition, it requires a fair
bit of complexity. Users also still need to install a bunch of dependencies, in
case ienv has to build from source.

As Inko matures, it will become more widely available through OS package
managers. For example, Inko is already available in Homebrew. This results in
duplication: all these package managers will have code to install Inko in a way
that works best for those OS', while we have a bunch of haphazardly thrown
together Makefiles to install Inko in tarballs.

Imagine for a moment Inko is available in every major package manager. A user
who simply wants to try out Inko is going to use their package manager, because
that's the easiest way to install Inko. They will never use ienv, and thus never
use our pre-compiled binaries.

A developer who actively uses Inko, and perhaps needs to have multiple versions
installed, will use ienv. But having pre-compiled binaries is not that big of a
deal. A clean release build of the VM takes about two minutes, of which a decent
amount of time is spent compiling libffi. If we dynamically link the system
libffi instead, this can be reduced by about 30-40 seconds. In addition,
developers won't install Inko versions that often: maybe once every few months.

Lastly, it's not clear how portable our binaries are, and ienv is not terribly
clever about figuring out if a binary can be used or not. This means binaries
may at some point stop working. To handle that we'd have to start building
binaries for multiple versions of all the OS' we want to support, increasing the
(financial) cost and effort; again all for few if any benefits.

This brings me to the following: unless I change my mind in the coming days, we
will stop building pre-compiled packages for macOS, Windows, and Linux. We will
then instead focus on making Inko available in package managers, and simplify
ienv accordingly, and maybe rewrite it in something saner than Bash; or replace
it with e.g. asdf. We will continue to build tarball archives though, as package
maintainers need these to build their packages.

As part of this we'd simply the Makefile setup such that only two install
related tasks exist:

1. `make build` this runs `cargo build` and such
1. `make install` this just moves the files in place (depending on `make build`)

This means the packaging process is essentially something like this:

```
make build
make install PREFIX=/usr DESTDIR=$PKGDIR
```

Where `$PKGDIR` is the path to the package building chroot/jail. `PREFIX` would
be used by the compiler to figure out where to find its source files.

## TODO

* [x] Remove Makefile code for the pre-compiled binaries
* [x] Rename the top-level `release` task to `publish`
* [x] Remove `runtime/Makefile`
* [x] Remove `compiler/Makefile`
* [x] Merge `vm/Makefile` into `./Makefile`
* [x] Add `make build` and `make install`. `make build` just builds the VM in release mode, while `make install` moves files into place
* [x] Remove ienv support for downloading pre-compiled packages
* [x] Include these changes in the `mkdocs` branch
