### ISSUE TITLE
(Re)introduce one-shot closures

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#347]
During the work on https://gitlab.com/inko-lang/inko/-/merge_requests/120, Inko briefly supported closures that could be called at most once, using the syntax `fn once { ... }`. This was later removed as I wasn't sure about their value.

Recently I've been spending time writing a small parsing combinator framework, mostly as a way of testing Inko's type system and to see what functionality might be missing. Several times I ran into cases where one-shot closures would be necessary. The simplest example is when you have `Option` A and `Option` B, and you want to map them into `(A, B)` like so:

```inko
a.then fn (lhs) { b.then fn (rhs) { Option.Some((lhs, rhs)) } }
```

This won't work because then the `b.then` closure captures `lhs`, it exposes it as `mut A`, meaning we end up with an `Option[(mut A, B)]` instead of `Option[(A, B)]`.

There are probably other cases where one-shot closures are useful. In fact, I think that _if_ we were to reintroduce them, we should recommend using them by default _unless_ you want to call a closure multiple times.

## Syntax

I prefer not to introduce the `once` keyword for _just_ this case, but it _is_ the most obvious/clear syntax:

```inko
fn once (arg) { ... }
```

I'm also not sure yet how to combine this with `fn move`: do we use `fn once move` or `fn move once`? Or does `fn once` simply imply `fn move`?

Another option is to use `fn!` instead of just `fn`, but this syntax isn't self-explanatory.

## Semantics

A one-shot closure's `call` method is generated as `fn move`, instead of `fn mut`. The captured variables are exposed using their original types (i.e. a captured `T` is exposed as `T`, not `mut T`). An `fn` isn't compatible with `fn once` and vice-versa.

## Tasks

- [ ] Decide on what the syntax will be for type signatures
- [ ] Decide on what the syntax will be for creating one-shot closure values. Or maybe we should just infer it?
- [ ] Implement the parser changes
- [ ] Implement in HIR
- [ ] Implement in the type checker
- [ ] Implement in MIR
- [ ] Change the standard library to use one-shot closures where desired

**Comment by yorickpeterse** [comment]
Another note: `fn move` currently results in _all_ captures being captured by moving. But what happens if we want to borrow captures A and B, and only move C? Right now there's no way of doing that.

**Comment by yorickpeterse** [comment]
One option is to make the list of captured variables explicit, i.e. something like this:

```inko
fn (arg1, arg2) move (capture1) { capture1.do_something(capture2) }
```

Here `capture1` would be captured by moving, while any other captures are captured by borrowing. This removes the need for doing this instead (a pattern not uncommon in Rust):

```inko
let capture2 = ref capture2

fn move (arg1, arg2) { capture1.do_something(capture2) }
```

**Comment by yorickpeterse** [comment]
Another option is this: if a closure moves some variable `A`, it's inferred as a moving closure and captures the variable as an owned value instead of a borrow. The problem now is that if we want to actually _borrow_ it (e.g. pass a borrow of it to a generic argument `T`), we need a way to explicitly signal that.

To put it differently, detecting whether a variable should be captured as a borrow or owned value is going to be tricky/prone to error.

**Comment by yorickpeterse** [comment]
I'm going to leave this be for the time being. Introducing one-shot closures introduces several challenges/complications, both for the compiler and the user. For example, for a one-shot closure to work it must capture variables by moving them. This means that a one-shot closure is always `fn move` but an `fn move` isn't necessarily a one-shot closure, which is confusing. 

In addition, our current "all or nothing" approach to capturing means that you can't have a one-shot closure that borrows certain values while taking ownership of others, instead they're either all borrowed or moved. This will make working with one-shot closures more difficult, resulting in a pattern similar to Rust as described in https://github.com/inko-lang/inko/issues/347#issuecomment-2263515315.

For cases where we have nested closures, such as the `Option.then` example, I think we're better off with dedicated methods to solve those issues, rather than introducing more complexity in the type system. One can also use a regular `match` expression if necessary.

If at some point in the future it's deemed necessary to have one-shot closures, we can revisit this.

**Comment by yorickpeterse** [comment]
There's another scenario where one-shot closures are very useful: DSLs for constructing trees or tree-like things. For example, an HTML DSL might look like this:

```inko
Html.new.table(fn (table) {
  table.tbody(fn (tbody) {
    for todo in todos {
      tbody.tr(fn (tr) {
        # ...
      })
    }
  })
})
```

This won't work unless we introduce oneshot closures, as otherwise `todos` is exposed as a borrow even if all closures are made annotated as `fn move`.

I've run into a few similar cases over time, so I think now is a good time to (re)introduce oneshot closures. We'll go with the following approach:

- There are no one-shot closure literals, instead this is inferred according to the type signature
- The type signature for oneshot is `fn move (arg, arg, ...)`
- `fn move` is only compatible with `fn move`, i.e. `fn move = fn move` and `fn ≠ fn move` and `fn move ≠ fn`
- `fn move` captures by moving since that's pretty much always what you want (= to move data _into_ the closure). We'll sort out the "but I want to borrow/move X" issues separately (e.g. using fn (arg1, arg2) move (var1, var2)` at some point

**Comment by yorickpeterse** [comment]
Working on https://github.com/inko-lang/inko/pull/903 highlighted an interesting/annoying problem:

Moving closures capturing by moving (instead of by borrowing) makes using them actually annoying in a lot of cases. For example, if a closure is meant to write to a `ByteArray` and is passed to an `fn move` argument, it will instead move the `ByteArray` into itself, making it impossible to use afterwards. 

To handle this, closures would still need to capture by borrowing by default, even if the closure is passed to an `fn move` closure. That however means that if you have a bunch of nested closures and you want to move data out of them, you need to annotate _all_ of them with `fn move`. This means you end up with something like this:

```inko
html.table(fn move (table) {
  table.tbody(fn move (tbody) {
    for todo in todos {
      tbody.tr(fn move (tr) { ... })
    }
  })
})
```

We _could_ make a nested `fn move` cascade upwards, but having to use `fn move` in some random place to make patterns like this work seems awfully confusing.

I also still can't get over the fact that an `fn move { ... }` literal is just a regular closure that captures by moving, while `fn move` in a type signature means a closure that captures by _borrows_ by default but just lets you move data out of the closure. Explicit/disjoint captures would resolve this by using syntax such as `fn (arg1, arg2) move (var1, var2) { ... }` but writing such closures is incredibly annoying and somewhat defeats their purpose/usefulness.

Rust handles this by deciding how variables are captured based on how they are used. For example, if an owned variable is captured but not moved then it could be captured by borrowing. Inko's compiler can't do this though because we determine the types of variables inside closures _before_ we perform move semantics/lifetime analysis, and changing that around would likely require extensive compiler changes.

The use case that prompted me to re-investigate this was a DSL for constructing HTML documents. In such cases you usually construct a deeply nested tree of closures, and somewhere in the middle you want to iterate over some data to produce e.g. a bunch of rows in a table. Being able to take ownership of the data in such a case means you can just use e.g. `for todo in todos`, which isn't possible if `todos` is a `mut Something`. I'm now not sure that getting moving closures to work is worth it for that particular use case. For example, if `Array` had a `drain` method that _didn't_ consume its receiver then you could just write `for todo in todos.drain` or something to that effect and get the same results.

Finally, in the case of generating documents there's also a pretty easy workaround: instead of fetching the data _before_ entering any of the closures, you do so somewhere in the middle. So instead of this:

```inko
let todos = get_todos

html.table(fn move (table) {
  table.tbody(fn move (tbody) {
    for todo in todos {
      tbody.tr(fn move (tr) { ... })
    }
  })
})
```

You do something like this:

```inko
html.table(fn move (table) {
  table.tbody(fn move (tbody) {
    for todo in get_todos {
      tbody.tr(fn move (tr) { ... })
    }
  })
})
```

This won't always work or be a nicer solution (i.e. you may want to keep the data retrieval logic separate), but it's an option.

Based on all of this I'm once again going to shelf the idea of moving/oneshot closures.
