### ISSUE TITLE
Rewrite the Ruby compiler's type system - [merged]

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#366]
_Merges new-type-system -> master_

Fixes https://gitlab.com/yorickpeterse/inko/issues/98

## TODO

* [x] Start by defining the individual type structures and write tests, instead of immediately hooking these up into the compiler.
* [x] Remove memoizing from the type database as this won't translate well to Inko (it's also not really necessary).
* [x] Get rid of `Type::Boolean` (somehow) in favour of just using `Type::Object`
* [x] Remove `Type::Nil` in favour of using `Type::Object` and the `std::marker::Optional` trait. This requires that types have access to the type database so they can look up types in other modules.
* [x] Split `Type::TypeParameterTable` into two separate structures: one for storing type parameters and one for mapping these to their instances
* [x] Spec out how type compatibility with regular objects is _actually_ supposed to work
* [x] Return `Type::Error` instead of `Type::Dynamic` when producing errors
* [x] Don't produce errors when sending messages to `Type::Error` to prevent cascading type errors
* [x] Determine how we should initialise generic types
* [x] Stop using the horrible `Inspect` module
* [x] ~~Change type parameter syntax from `!(X, Y, Z)` to `[X, Y, Z]`. This is easier to type (on a QWERTY keyboard it doesn't require the use of shift).~~
