### ISSUE TITLE
Add the ability to obtain human-readable representations of objects - [merged]

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#367]
_Merges inspect -> master_

The Inspect trait defines a single method, called "inspect". This is necessary for the upcoming `std::test` library discussed in https://gitlab.com/yorickpeterse/inko/issues/100.

## TODO

* [x] Add a StringBuffer object, for efficiently concatenating Strings
* [x] Extend the StringConcat VM instruction so it can concatenate an arbitrary number of Strings.
* [x] Use StringBuffer for `Object.inspect` and `Array.inspect`
