### ISSUE TITLE
Rework IO - [merged]

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#368]
_Merges rework-io -> master_

This completely reworks the IO system of Inko, using proper byte array types where necessary, instead of using an array of integers. See c5897da0565cadaf1c2f52cf61e6978cab4eb2e7 for more details.

This fixes #108 

# TODO

* [x] `Close.close` should throw
* [x] Change the documentation of `Close` to indicate it's for closing files, sockets, etc, and not for disposing of regular objects
* [x] `read` should be given a required `buffer` argument, of type `Array!(Integer)`. Data is read into this buffer, instead of returning a new array.
* [x] `read` should be given an optional `size` argument. If given, only `size` bytes are read, otherwise all remaining bytes are read.
* [x] `read_string` should be added, which reads up to `size` bytes (or all remaining ones), and returns the result as a String
* [x] Reading a single line should be implemented in just Inko, and the VM instructions should be removed
* [x] `write` takes a `Array!(Integer)`, instead of a `String`
* [x] `write_string` takes a `String`
* [x] `StringFromBytes` should optionally drain the input Array. This allows for more efficient reading of data and converting it to a string, without relying on VM code.
* [x] Clean up `std::fs::file` using the `object ... impl` syntax
