### ISSUE TITLE
Implement Inko's parser in Inko - [merged]

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#425]
_Merges std-compiler-parser -> master_

## Details

The parser is an LL(1) recursive descent parser. While the Ruby parser
was used as a reference, it is not a 1:1 port.

As part of porting the parser to Inko, several syntax changes were made:

1. "where" on methods is not supported by the Inko parser. When we start
   using the parser we will move "where" to traits.

2. The comments "#!" and "##" are replaced with just "#". This makes the
   lexer and parser internals easier, and removes the need for having to
   remember three different comment types.

3. Mutable rest arguments are supported in the Inko parser using
   "mut *NAME", instead of "* mut NAME".

Using the parser is straightforward:

    import std::compiler::parser::Parser

    let parser = Parser.new(input: '10 + 2', file: 'test.inko')

    try! parser.parse

The AST nodes are located in modules under `std::compiler::ast`. For
example, integer literals are in `std::compiler::ast::literals`. For now
there is some minor duplication across some of the AST nodes. For
example, the types of methods (MethodDefinition) and required methods
(RequiredMethodDefinition) are similar. When we start implementing the
compiler we may change this around a bit, or perhaps split the AST nodes
into more separate types.

Fixes https://gitlab.com/inko-lang/inko/issues/172

## TODO

Tokens to support as a value:

* [x] attribute
* [x] colon_colon
* [x] constant
* [x] define
* [x] identifier
* [x] let
* [x] return
* [x] self
* [x] static
* [x] throw
* [x] try
* [x] try_bang
* [x] slicing syntax
* [x] comment
* [x] curly_open
* [x] do
* [x] documentation
* [x] float
* [x] integer
* [x] lambda
* [x] paren_open
* [x] string

Other tasks to complete:

* [x] Parse required methods
* [x] Parse comments inside parentheses
    * This brings up an interesting question: how should we handle comments? Module/documentation comments can only occur in certain places, but regular comments can go everywhere (e.g. inside parentheses). These comments should be available somehow so we can go from source to AST and back, without losing them.
* [x] Parse rest arguments
* [x] Parse mutable arguments
* [x] Parse import wildcards
* [x] Run the parser over the runtime to see if it parses everything. 
    * :warning: Since it does not support method bounds it will error out on code that uses this.
* [x] Organise the parser code a bit better so there are fewer AST modules and random helper methods

## Corresponding issue

https://gitlab.com/inko-lang/inko/issues/172

## Checklist

* [x] Added tests
* [x] Added documentation
* [x] Inko source code follows the [Inko style guide](https://inko-lang.org/manual/style-guide/)
