### ISSUE TITLE
Add cryptography ciphers/algorithms

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#499]
Original GitLab issue: https://gitlab.com/inko-lang/inko/-/issues/283

---

Inko's standard library should provide support for commonly used cryptographic ciphers/algorithms, such as MD5, SHA1, etc, and whatever ciphers we need for TLS/SSL support (see https://gitlab.com/inko-lang/inko/-/issues/262). 

Specifically I'm thinking of _at least_ the following ones:

- MD5 (even though it's broken it's still in use)
- SHA1, SHA2, not sure if SHA3 is widely used
- Blake2, because you should basically use this instead of SHA/MD5 whenever possible
- ChaCha20 (TLS requires this I believe)
- Whatever else we need for TLS 1.x

All of this should be implemented in pure Inko, as I don't want to add dozens of additional built-in functions, Rust wrapper types, etc.

## TODO

- [x] MD5: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] SHA1: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] SHA256: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] SHA512: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] ChaCha20: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] XChaCha20: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] Poly1305: https://gitlab.com/inko-lang/inko/-/merge_requests/131
- [x] ~~ChaCha20-Poly1305~~: https://github.com/inko-lang/inko/issues/574
- [x] ~~XChaCha20-Poly1305~~: https://github.com/inko-lang/inko/issues/574
- [x] ~~BigInt with constant-time operations (so we don't have to implement this ad-hoc every time)~~ scapped for now unless we really need it
- [x] ~~X509:~~ https://github.com/inko-lang/inko/issues/572
- [x] ~~AES:~~ https://github.com/inko-lang/inko/issues/573

Not all of these need to be implemented at once/right now. For example, X509 and secp256k1 support is something we should wait with until we're ready to start working on a TLS stack. Given my limited knowledge of cryptography we'd also need to get other people involved, as I'll inevitably implement something incorrectly.

**Comment by yorickpeterse** [comment]
Closing this in favour of the various individual issues I just created.
