### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#534]
This version will include the native code compiler, replacing the bytecode interpreter.

## TODO

- [ ] Do some additional testing with https://github.com/yorickpeterse/openflow to see if there are any bugs that we really should fix before the release
- [ ] Build a package and test it with [ivm](https://github.com/inko-lang/ivm), to make sure the build process still works
- [ ] Update the website examples for the new version
- [ ] Update the homepage feature highlights
- [ ] Write a release post
- [ ] Test if pushing the tag still works
