### ISSUE TITLE
Implement socket IO using pure Inko

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#752]
With https://github.com/inko-lang/inko/issues/633 fixed, we should do the same for socket IO.

The following functions need to be replaced:

- [x] `inko_socket_accept`
- [x] `inko_socket_bind`
- [x] `inko_socket_connect`
- [x] `inko_socket_drop`
- [x] `inko_socket_listen`
- [x] `inko_socket_local_address`
- [x] `inko_socket_new`
- [x] `inko_socket_peer_address`
- [x] `inko_socket_read`
- [x] `inko_socket_receive_from`
- [x] `inko_socket_send_bytes_to`
- [x] `inko_socket_send_string_to`
- [x] `inko_socket_shutdown_read_write`
- [x] `inko_socket_shutdown_read`
- [x] `inko_socket_shutdown_write`
- [x] `inko_socket_try_clone`
- [x] `inko_socket_write`

## TODO

- [x] Replace `inko_socket_*` functions with pure Inko code
- [x] Adjust TLS code to use callbacks instead of directly depending on the `Socket` type

## Reading material

- https://github.com/rust-lang/rust/issues/69061

**Comment by yorickpeterse** [comment]
There's a tricky aspect to this: for TLS sockets we need to create a rustls `Stream` type, which in turn requires a type that implements `Read` and `Write`. This won't be the case when using a raw file descriptor, or any other type provided by Inko's standard library. So for TLS sockets to do their reads/writes/etc using Inko code, we'd need to replace usage of the `Stream` type with more low-level primitives, but even then it might not be possible to avoid the use of the `Read` and `Write` types.

**Comment by yorickpeterse** [comment]
To handle the case of TLS, we'd need a callback based approach: functions such as `inko_tls_client_read` take a function pointer as a callback and call this to perform the actual read. The signature of the callback would likely need to be `fn (socket: Int32, buffer: Pointer[UInt8], size: UInt64, read: Pointer[UInt64]) -> Int32`, where `size` is the number of bytes to read and `read` the number of bytes read. The return value would be `0` in case of success, or an `errno` value in case of an error.

The downside is that reads and writes now require at least two function calls: one for calling the runtime library function, and one to call the callback function.

The benefit is that we can fully move the read/write implementations into the standard library.
