### ISSUE TITLE
Replace the `class` keyword with the `type` keyword

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#779]
### Description

In https://github.com/inko-lang/inko/pull/778 I'm introducing support for user-defined stack allocated types. In pretty much all languages out there that have a notion of classes, the `class` keyword is typically used for a heap allocated type that you address through a pointer, and something like a `struct` keyword is used (if supported at all) for stack types.

This means that seeing `class inline Foo { ... }` is a bit odd, because `class` might have you believe it's a heap type, while `inline` means it's in fact a stack type.

To resolve this, we'll replace the `class` keyword with the `type` keyword. So instead of this:

```inko
class User { ... }
class inline Number { ... }
```

You'd write the following:

```inko
type User { ... }
type inline Number { ... }
```

For traits we'll continue to use the `trait` keyword as there's no benefit to changing it.

## TODO

- [x] Support both `class` and `type` at the parser level
- [x] Update the Tree sitter grammar to support both `class` and `type`
- [x] Update Vim syntax file
- [x] Update VS Code extension
- [x] Update the code formatter to replace `class` with `type` automatically
- [x] Update the documentation
